version: '3.7'

networks:
  traefik:
    external:
      name: traefik

volumes:
  storage:
    name: hello-world-storage
  postgres-data:
    name: hello-world-postgres-data

services:
  hello-world:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    init: true
    env_file: .env
    mem_limit: 300m
    memswap_limit: 1g
    cpu_shares: 2
    expose:
      - '80'
    volumes:
      - storage:/app/storage
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.hello-world.rule=Host(`hello-world.example.com`)"
      - "traefik.http.routers.hello-world.service=hello-world-service"
      # httpS
      - "traefik.http.routers.hello-world-tls.rule=Host(`hello-world.example.com`)"
      - "traefik.http.routers.hello-world-tls.tls.certResolver=default"
      - "traefik.http.routers.hello-world-tls.service=hello-world-service"
      # to which port of this container Traefik should route all traffic
      - "traefik.http.services.hello-world-service.loadbalancer.server.port=80"

  postgres:
    image: 'postgres:14.2-alpine'
    restart: always
    # log ALL queries. REMOVE after tests:
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD
      - CUSTOM_POSTGRES_DB
      - CUSTOM_POSTGRES_USER
